version: '3'
services:
  fdb:
    image: foundationdb/foundationdb:7.3.43
    ports:
      - 4550:4550/tcp
    environment:
      FDB_NETWORKING_MODE: host
      FDB_COORDINATOR_PORT: 4550
      FDB_PORT: 4550
    volumes:
      - ./datadir/fdb:/var/fdb/data/:rw,z
